#!/usr/bin/env python3
"""
phase2_resign.py
Re-signs an APK after Phase 2 patches.
Uses the SAME keystore generated by KeystoreGeneratorPlugin (Gradle build)
so the final APK has one consistent certificate — not a second random one.

Usage: python3 scripts/phase2_resign.py <apk_path>
"""
import sys, os, secrets, random, subprocess, glob

APK = sys.argv[1] if len(sys.argv) > 1 else ""
if not APK or not os.path.isfile(APK):
    print(f"❌ APK not found: {APK}")
    sys.exit(1)

# ── Try to read keystore from KeystoreGeneratorPlugin creds file ──────────────
# Written by Gradle to app/build/keystore/ks_creds_app.properties
creds_files = glob.glob("app/build/keystore/ks_creds_*.properties")
KS = ALIAS = PW = None

if creds_files:
    creds_file = sorted(creds_files)[-1]
    print(f"[phase2_resign] Reading keystore creds from: {creds_file}")
    props = {}
    with open(creds_file) as f:
        for line in f:
            line = line.strip()
            if '=' in line:
                k, v = line.split('=', 1)
                props[k.strip()] = v.strip()
    KS    = props.get('ks_file')
    PW    = props.get('ks_pass')
    ALIAS = props.get('ks_alias')

    if KS and os.path.isfile(KS) and PW and ALIAS:
        print(f"[phase2_resign] ✅ Using Gradle keystore: {os.path.basename(KS)}")
    else:
        print(f"[phase2_resign] ⚠️ Creds incomplete — falling back to fresh keystore")
        KS = ALIAS = PW = None

# ── Fallback: generate fresh keystore if Gradle one not available ─────────────
if not KS:
    NAMES     = ["Rahul Sharma","Priya Verma","Amit Patel","Sneha Iyer",
                 "Vikram Singh","Deepika Nair","Arjun Mehta","Pooja Gupta",
                 "Alice","Bob","Charlie","David","Grace","Frank"]
    ORGS      = ["Bharat Digital Services","India Tech Solutions",
                 "Desi Apps Studio","Hindustan Mobile Works",
                 "Acme Corp","Bright Solutions","Cloud Nine","Delta Systems"]
    COUNTRIES = ["IN","IN","IN","US","GB","DE","FR","CA"]

    cn    = random.choice(NAMES)
    o     = random.choice(ORGS)
    c     = random.choice(COUNTRIES)
    alias = "key_" + secrets.token_hex(4)
    pw    = secrets.token_urlsafe(16)
    ks    = APK + ".p2resign.jks"
    val   = random.randint(730, 3650)

    print(f"[phase2_resign] Generating fresh keystore: CN={cn} O={o} C={c}")
    r = subprocess.run([
        "keytool","-genkeypair","-storetype","JKS",
        "-keystore", ks, "-alias", alias,
        "-keyalg","RSA","-keysize","2048","-validity",str(val),
        "-storepass", pw, "-keypass", pw,
        "-dname", f"CN={cn}, O={o}, C={c}",
        "-noprompt"
    ], capture_output=True, text=True)
    if r.returncode != 0:
        print(f"❌ keytool failed: {r.stderr}")
        sys.exit(1)
    KS = ks; PW = pw; ALIAS = alias

# ── Zipalign ──────────────────────────────────────────────────────────────────
aligned = APK + ".p2aligned"
subprocess.run(["zipalign","-f","4", APK, aligned], capture_output=True)
if os.path.isfile(aligned):
    os.replace(aligned, APK)

# ── Sign V1+V2+V3 ─────────────────────────────────────────────────────────────
print(f"[phase2_resign] Signing {os.path.basename(APK)} V1+V2+V3")
r2 = subprocess.run([
    "apksigner","sign",
    "--min-sdk-version","28",  # prevents apksigner reading minSdk from stub arsc/manifest
    "--ks", KS,
    "--ks-key-alias", ALIAS,
    "--ks-pass", f"pass:{PW}",
    "--key-pass", f"pass:{PW}",
    "--v1-signing-enabled","true",
    "--v2-signing-enabled","true",
    "--v3-signing-enabled","true",
    APK
], capture_output=True, text=True)
if r2.returncode != 0:
    print(f"❌ apksigner failed: {r2.stderr}")
    sys.exit(1)

# Clean up fresh keystore if we generated one
if KS.endswith(".p2resign.jks") and os.path.isfile(KS):
    os.remove(KS)

print(f"[phase2_resign] ✅ {os.path.basename(APK)} re-signed")
