/**
 * chunk_constants.h — Phase 4
 * Auto-generated by scripts/chunk_constants_gen.py during CI build.
 * DO NOT EDIT — overwritten every build.
 *
 * Contains XOR-masked chunk offsets, sizes, AES key parts, integrity hashes.
 * All sensitive values XOR-masked with split key (never appears as single literal).
 */

#ifndef CHUNK_CONSTANTS_H
#define CHUNK_CONSTANTS_H

#include <stdint.h>

/* ── Build identity ─────────────────────────────────────── */
/* Set by chunk_constants_gen.py via CMake -D flags or hardcoded per build */

#define N_CHUNKS 0  /* Overwritten by CI */

/* XOR mask key — split, never a single literal */
#define XK_HI 0x0000
#define XK_LO 0x0000
#define XOR_KEY ((uint32_t)((XK_HI << 16) | XK_LO))

/* Unmask a value */
#define UNMASK(v) ((uint32_t)(v) ^ XOR_KEY)
#define UNMASK_OFFSET(v) ((uint64_t)UNMASK(v))
#define UNMASK_SIZE(v)   ((uint32_t)UNMASK(v))

/* ── Masked AES-256 key (8 x 32-bit masked ints) ────────── */
/* Overwritten by CI */
static const uint32_t MASKED_KEY[8] = {0,0,0,0,0,0,0,0};

/* ── Masked AES GCM IV (3 x 32-bit masked ints) ─────────── */
static const uint32_t MASKED_IV[3] = {0,0,0};

/* ── Integrity hashes ────────────────────────────────────── */
#define SHA256_HASH ""
#define SHA512_HASH_A ""
#define SHA512_HASH_B ""

/* ── Per-chunk data (populated by CI via generated header) ── */
/* chunk_data.h is generated per build and included below */

/* Chunk .so names */
static const char* CHUNK_SO_NAMES[] = {
    "libdatabridge.so",   /* chunk 0 */
    "libsyncworker.so",   /* chunk 1 */
    "libfilehandler.so",  /* chunk 2 */
    "libcachemanager.so", /* chunk 3 */
    "libtaskrunner.so",   /* chunk 4 */
    "libworkagent.so",    /* chunk 5 */
    "libresmanager.so",   /* chunk 6 */
    "libnetbridge.so",    /* chunk 7 */
};

/* Masked offsets and sizes for arm64-v8a */
static const uint32_t CHUNK_MOFF_64[] = {0,0,0,0,0,0,0,0};
static const uint32_t CHUNK_MSZ_64[]  = {0,0,0,0,0,0,0,0};

/* Masked offsets and sizes for armeabi-v7a */
static const uint32_t CHUNK_MOFF_32[] = {0,0,0,0,0,0,0,0};
static const uint32_t CHUNK_MSZ_32[]  = {0,0,0,0,0,0,0,0};

#endif /* CHUNK_CONSTANTS_H */
